/*
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018-01-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package api;

import invoker.ApiException;
import invoker.Environment;
import invoker.FinixClient;
import model.*;
import org.junit.jupiter.api.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * API tests for SubscriptionSchedulesApi
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@DisplayName("When Running SubscriptionSchedulesApiTest")
@Disabled
public class SubscriptionSchedulesApiTest {
    private FinixClient finixClient;
    private final SubscriptionSchedulesApi api = new SubscriptionSchedulesApi();
    @Test
    @BeforeAll
    @DisplayName("Finix Client")
    void contextLoads() {
        finixClient= new FinixClient("UStxEci4vXxGDWLQhNvao7YY","25038781-2369-4113-8187-34780e91052e", Environment.SANDBOX);
        //  System.out.println(finixClient == null);
        assertEquals(true , finixClient!=null);

    }
    /**
     * List Subscription Schedules
     *
     * Retrieve a list of &#x60;Subscription Schedules&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    @DisplayName("List Subscription Schedules\n")
    public void getSubscriptionSchedulesTest() throws ApiException {
        String nickname = null;
        String type = null;
        SubscriptionSchedulesList response = finixClient.SubscriptionSchedules.list(nickname, type);
        // TODO: test validations
    }

    /**
     * Get a Subscription Schedule
     *
     * Retrieve the details of a &#x60;subscription_schedule&#x60;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSubscriptionSubscriptionSchedulesIdTest() throws ApiException {
        String subscriptionScheduleId = null;
        String nickname = null;
        String type = null;
        SubscriptionSchedule response = api.get(subscriptionScheduleId, nickname, type);
        // TODO: test validations
    }

    /**
     * Create a Subscription Schedule
     *
     * Create a &#x60;subscription_schedule&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    @DisplayName("Create Subscription Schedule FIXED_TIME_INTERVAL")
    public void postFixedTimeSubscriptionSubscriptionSchedulesTest() throws ApiException {
        CreateSubscriptionScheduleRequest createSubscriptionScheduleRequest = CreateSubscriptionScheduleRequest.builder()
                .lineItemType(CreateSubscriptionScheduleRequest.LineItemTypeEnum.FEE)
                .nickname("Fixed_Time_Subscription_Schedule")
                .fixedTimeIntervalOffset(CreateSubscriptionScheduleRequestFixedTimeIntervalOffset.builder()
                        .intervalCount(4)
                        .hourlyInterval(24)
                        .build())
                .subscriptionType(CreateSubscriptionScheduleRequest.SubscriptionTypeEnum.FIXED_TIME_INTERVAL)
                .build();
        SubscriptionSchedule response = finixClient.SubscriptionSchedules.create(createSubscriptionScheduleRequest);
        // TODO: test validations
    }
    @Test
    @DisplayName("Create Subscription Schedule PERIODIC_MONTHLY")
    public void postPeriodicMonthlySubscriptionSubscriptionSchedulesTest() throws ApiException {
        CreateSubscriptionScheduleRequest createSubscriptionScheduleRequest = CreateSubscriptionScheduleRequest.builder()
                .lineItemType(CreateSubscriptionScheduleRequest.LineItemTypeEnum.FEE)
                .periodOffset(CreateSubscriptionScheduleRequestPeriodOffset.builder()
                        .day(1)
                        .month(null)
                        .build())
                .nickname("Monthly_Subscription_Schedule")
                .subscriptionType(CreateSubscriptionScheduleRequest.SubscriptionTypeEnum.PERIODIC_MONTHLY)
                .build();
        SubscriptionSchedule response = finixClient.SubscriptionSchedules.create(createSubscriptionScheduleRequest);
        // TODO: test validations
    }

    @Test
    @DisplayName("Create Subscription Schedule PERIODIC_YEARLY")
    public void postPeriodicYearlySubscriptionSubscriptionSchedulesTest() throws ApiException {
        CreateSubscriptionScheduleRequest createSubscriptionScheduleRequest = CreateSubscriptionScheduleRequest.builder()
                .lineItemType(CreateSubscriptionScheduleRequest.LineItemTypeEnum.FEE)
                .periodOffset(CreateSubscriptionScheduleRequestPeriodOffset.builder()
                        .day(5)
                        .month(1)
                        .build())
                .nickname("Yearly_Subscription_Schedule")
                .subscriptionType(CreateSubscriptionScheduleRequest.SubscriptionTypeEnum.PERIODIC_YEARLY)
                .build();
        SubscriptionSchedule response = finixClient.SubscriptionSchedules.create(createSubscriptionScheduleRequest);
        // TODO: test validations
    }

    /**
     * Update a Subscription Schedule
     *
     * Update the details of a &#x60;subscription_schedule&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void putSubscriptionSubscriptionSchedulesIdTest() throws ApiException {
        String subscriptionScheduleId = null;
        UpdateSubscriptionScheduleRequest updateSubscriptionScheduleRequest = null;
        SubscriptionSchedule response = api.update(subscriptionScheduleId, updateSubscriptionScheduleRequest);
        // TODO: test validations
    }

}
