/*
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018-01-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import model.ApplicationLinksSelf;
import model.ApplicationProfileLinksApplication;
import model.AuthorizationLinksDevice;
import model.AuthorizationLinksMerchantIdentity;
import model.AuthorizationLinksTransfer;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AuthorizationLinks
 */
public class AuthorizationLinksTest {
    private final AuthorizationLinks model = new AuthorizationLinks();

    /**
     * Model tests for AuthorizationLinks
     */
    @Test
    public void testAuthorizationLinks() {
        // TODO: test AuthorizationLinks
    }

    /**
     * Test the property 'application'
     */
    @Test
    public void applicationTest() {
        // TODO: test application
    }

    /**
     * Test the property 'device'
     */
    @Test
    public void deviceTest() {
        // TODO: test device
    }

    /**
     * Test the property 'merchantIdentity'
     */
    @Test
    public void merchantIdentityTest() {
        // TODO: test merchantIdentity
    }

    /**
     * Test the property 'self'
     */
    @Test
    public void selfTest() {
        // TODO: test self
    }

    /**
     * Test the property 'transfer'
     */
    @Test
    public void transferTest() {
        // TODO: test transfer
    }

}
