/*
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018-01-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import model.CreatePaymentInstrumentRequestAddress;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreatePaymentInstrumentRequest
 */
public class CreatePaymentInstrumentRequestTest {
    private final CreatePaymentInstrumentRequest model = new CreatePaymentInstrumentRequest();

    /**
     * Model tests for CreatePaymentInstrumentRequest
     */
    @Test
    public void testCreatePaymentInstrumentRequest() {
        // TODO: test CreatePaymentInstrumentRequest
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'expirationMonth'
     */
    @Test
    public void expirationMonthTest() {
        // TODO: test expirationMonth
    }

    /**
     * Test the property 'expirationYear'
     */
    @Test
    public void expirationYearTest() {
        // TODO: test expirationYear
    }

    /**
     * Test the property 'identity'
     */
    @Test
    public void identityTest() {
        // TODO: test identity
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'securityCode'
     */
    @Test
    public void securityCodeTest() {
        // TODO: test securityCode
    }

}
