/*
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import model.Error401UnauthorizedEmbeddedErrorsInnerLinks;
import model.LogRef;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Error401UnauthorizedEmbeddedErrorsInner
 */
public class Error401UnauthorizedEmbeddedErrorsInnerTest {
    private final Error401UnauthorizedEmbeddedErrorsInner model = new Error401UnauthorizedEmbeddedErrorsInner();

    /**
     * Model tests for Error401UnauthorizedEmbeddedErrorsInner
     */
    @Test
    public void testError401UnauthorizedEmbeddedErrorsInner() {
        // TODO: test Error401UnauthorizedEmbeddedErrorsInner
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'logref'
     */
    @Test
    public void logrefTest() {
        // TODO: test logref
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
