/*
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018-01-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import model.ApplicationLinksApplicationProfile;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Error422InvalidFieldListEmbeddedLinks
 */
public class Error422InvalidFieldListEmbeddedLinksTest {
    private final Error422InvalidFieldListEmbeddedLinks model = new Error422InvalidFieldListEmbeddedLinks();

    /**
     * Model tests for Error422InvalidFieldListEmbeddedLinks
     */
    @Test
    public void testError422InvalidFieldListEmbeddedLinks() {
        // TODO: test Error422InvalidFieldListEmbeddedLinks
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

}
