/*
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018-01-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import model.ApplicationLinksApplicationProfile;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InstrumentUpdateLinks
 */
public class InstrumentUpdateLinksTest {
    private final InstrumentUpdateLinks model = new InstrumentUpdateLinks();

    /**
     * Model tests for InstrumentUpdateLinks
     */
    @Test
    public void testInstrumentUpdateLinks() {
        // TODO: test InstrumentUpdateLinks
    }

    /**
     * Test the property 'application'
     */
    @Test
    public void applicationTest() {
        // TODO: test application
    }

    /**
     * Test the property 'paymentInstrument'
     */
    @Test
    public void paymentInstrumentTest() {
        // TODO: test paymentInstrument
    }

    /**
     * Test the property 'self'
     */
    @Test
    public void selfTest() {
        // TODO: test self
    }

}
