/*
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ListIdentitiesQueryParams
 */
public class ListIdentitiesQueryParamsTest {
    private final ListIdentitiesQueryParams model = new ListIdentitiesQueryParams();

    /**
     * Model tests for ListIdentitiesQueryParams
     */
    @Test
    public void testListIdentitiesQueryParams() {
        // TODO: test ListIdentitiesQueryParams
    }

    /**
     * Test the property 'sort'
     */
    @Test
    public void sortTest() {
        // TODO: test sort
    }

    /**
     * Test the property 'afterCursor'
     */
    @Test
    public void afterCursorTest() {
        // TODO: test afterCursor
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdAtGte'
     */
    @Test
    public void createdAtGteTest() {
        // TODO: test createdAtGte
    }

    /**
     * Test the property 'createdAtLte'
     */
    @Test
    public void createdAtLteTest() {
        // TODO: test createdAtLte
    }

    /**
     * Test the property 'defaultStatementDescriptor'
     */
    @Test
    public void defaultStatementDescriptorTest() {
        // TODO: test defaultStatementDescriptor
    }

    /**
     * Test the property 'businessName'
     */
    @Test
    public void businessNameTest() {
        // TODO: test businessName
    }

    /**
     * Test the property 'businessType'
     */
    @Test
    public void businessTypeTest() {
        // TODO: test businessType
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'beforeCursor'
     */
    @Test
    public void beforeCursorTest() {
        // TODO: test beforeCursor
    }

}
