/*
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018-01-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import model.ApplicationLinksApplicationProfile;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SettlementLinks
 */
public class SettlementLinksTest {
    private final SettlementLinks model = new SettlementLinks();

    /**
     * Model tests for SettlementLinks
     */
    @Test
    public void testSettlementLinks() {
        // TODO: test SettlementLinks
    }

    /**
     * Test the property 'application'
     */
    @Test
    public void applicationTest() {
        // TODO: test application
    }

    /**
     * Test the property 'credits'
     */
    @Test
    public void creditsTest() {
        // TODO: test credits
    }

    /**
     * Test the property 'debits'
     */
    @Test
    public void debitsTest() {
        // TODO: test debits
    }

    /**
     * Test the property 'disputes'
     */
    @Test
    public void disputesTest() {
        // TODO: test disputes
    }

    /**
     * Test the property 'fees'
     */
    @Test
    public void feesTest() {
        // TODO: test fees
    }

    /**
     * Test the property 'fundingTransfers'
     */
    @Test
    public void fundingTransfersTest() {
        // TODO: test fundingTransfers
    }

    /**
     * Test the property 'identity'
     */
    @Test
    public void identityTest() {
        // TODO: test identity
    }

    /**
     * Test the property 'reversals'
     */
    @Test
    public void reversalsTest() {
        // TODO: test reversals
    }

    /**
     * Test the property 'self'
     */
    @Test
    public void selfTest() {
        // TODO: test self
    }

    /**
     * Test the property 'transfers'
     */
    @Test
    public void transfersTest() {
        // TODO: test transfers
    }

}
